### ISSUE TITLE
Hitting 'start over' and navigating to the same page creates duplicate 'fuck yeah. now what?' buttons

### ISSUE THREAD

**Issue by euro-fly** [csb324/holyfucktheelectionistomorrow#20]
As above.

This is what happens when you go from "I'm ready to fuck shit up" -> "Electing some fucking democrats" -> "Money" three times:

![fuck yeah now what 3](https://cloud.githubusercontent.com/assets/7606386/20333863/895be726-ab6a-11e6-9d52-021a05ed3dad.PNG)

I've observed this happening on all of the categories, for both "Money" and "Time." I feel like an extra button is just being added whenever this happens, but I'll need to investigate further.

Will try working on it. PR forthcoming? Maybe?

**Comment by euro-fly** [comment]
Addressed in #21

**Comment by csb324** [comment]
Thank you for solving this!
