### ISSUE TITLE
Predator Elect

### ISSUE THREAD

**Issue by predatorelect** [csb324/holyfucktheelectionistomorrow#36]
@csb324,

I just wanted to say **THANK YOU**. You were one of the main sources of inspiration for me to make my site at the domain [Predator Elect](http://predatorelect.us), although I didn't go the full on React route like you did (I felf that it was a bit overkill for my site).

It took just 88¢ to register the domain and a few hours of my Saturday to put together [predatorelect.us](http://predatorelect.us) to encourage donations to some non-profit women's organizations. And they desperately need our help!

Donavon

p.s. I hope you don't mind, but I credited you as a source of inspiration in my footer. 

[![Visit Predator Elect](https://cloud.githubusercontent.com/assets/23579932/20463566/09f4daf4-af04-11e6-8d4a-33c9b79d37e0.png)](http://predatorelect.us/)

**Comment by csb324** [comment]
this is awesome!! thanks for sharing it!
